API:
  PORT: 4000

DATABASE:
  TYPE: 'postgres'
  SYNCHRONIZE: true

JWT:
  EXPIRES_IN: '99999h'
  SECRET: 'FKdksk12l3ldlsfdlLlsdll123l05kgjgk04jdkgn6kk2d0fkgsdk32ldovyjkxg'

FACEBOOK:
  CLIENT_ID: '168878955342230'
  CLIENT_SECRET: 'd8b62ef1da6ba65940f90f373d4463b1'
  CALLBACK_URL: 'https://pocket-look.herokuapp.com/auth/facebook/redirect'

GOOGLE:
  CLIENT_ID: '857571824635-s9u3bhlc806ullpgiib8d626csnjh0de.apps.googleusercontent.com'
  CLIENT_SECRET: 'ENwlRXt3vnRohU8hFNbAcQjf'
  CALLBACK_URL: 'http://localhost:4000/auth/google/redirect'

AWS:
  SECRET_ACCESS_KEY: '37T4L1AKRY0tAtJXC7b+FmOCEUFVOoyeMSCx0TGr'
  ACCESS_KEY_ID: 'AKIAIE6IJHPEO346SJ7Q'
  REGION: 'us-east-2'
  BUCKET_NAME: 'testdownloadimagesbucket'
  ACL: 'public-read'
